name: Build and Run Tests

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
  scheme: Logs
  build_filetype: project
  filename: Logs.xcodeproj
  platform: iOS Simulator
  device: iPhone 11

jobs:
  build:
    name: Build and Test Logs Scheme on iPhone 11 simulator
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -"$build_filetype" "$filename" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$scheme" -"$build_filetype" "$filename" -destination "platform=$platform,name=$device"
