name: Build and Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
  scheme: Logs
  build_filetype: project
  filename: Logs.xcodeproj
  platform: iOS Simulator
  device: iPhone 11

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -"$build_filetype" "$filename" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$scheme" -"$build_filetype" "$filename" -destination "platform=$platform,name=$device"
